import type { DataProfile } from "../dataProfile";

export const invoiceProfile: DataProfile = {
  id: "invoice",

  name: "Invoice Import",

  description:
    "Validate and prepare invoice data for safe import into business systems.",

  fields: [
    {
      key: "invoice_number",
      label: "Invoice Number",
      required: true,
      synonyms: [
        "invoice",
        "invoice number",
        "invoice no",
        "invoice id",
        "invoice_id",
        "invoice nr",
        "invoice reference",
        "invoice ref",
        "invoice code",
        "invoice_code",
        "factuur",
        "factuurnummer",
        "factuur nummer",
        "factuurnr",
        "factuur nr",
        "document",
        "document number",
        "document no",
        "document id",
        "document_no",
        "doc no",
        "doc number",
        "ref",
        "reference",
        "reference number",
        "number",
      ],
    },

    {
      key: "company",
      label: "Company",
      required: true,
      synonyms: [
        "company",
        "company name",
        "client",
        "client name",
        "customer",
        "customer name",
        "account",
        "account name",
        "business",
        "business name",
        "organization",
        "organisation",
        "bedrijf",
        "bedrijfsnaam",
        "klant",
        "klantnaam",
        "debiteur",
        "debtor",
        "debtor name",
      ],
    },

    {
      key: "email",
      label: "Email",
      required: true,
      synonyms: [
        "email",
        "e-mail",
        "mail",
        "email address",
        "customer email",
        "client email",
        "billing email",
        "invoice email",
        "contact email",
        "contact mail",
        "finance email",
        "debtor email",
        "factuur email",
        "factuurmail",
      ],
    },

    {
      key: "amount",
      label: "Amount",
      required: true,
      synonyms: [
        "amount",
        "invoice amount",
        "invoice total",
        "total",
        "total amount",
        "grand total",
        "gross total",
        "gross_amount",
        "net amount",
        "net_amount",
        "subtotal",
        "price",
        "value",
        "bedrag",
        "factuurbedrag",
        "totaal",
        "totaalbedrag",
        "netto",
        "bruto",
      ],
    },

    {
      key: "vat",
      label: "VAT",
      required: true,
      synonyms: [
        "vat",
        "vat amount",
        "vat total",
        "tax",
        "tax amount",
        "tax total",
        "sales tax",
        "btw",
        "btw bedrag",
        "btw totaal",
        "belasting",
        "belastingbedrag",
      ],
    },

    {
      key: "status",
      label: "Status",
      required: false,
      synonyms: [
        "status",
        "state",
        "payment status",
        "invoice status",
        "workflow status",
        "workflow",
        "stage",
        "fase",
        "betaling status",
        "betaalstatus",
      ],
    },

    {
      key: "country",
      label: "Country",
      required: false,
      synonyms: [
        "country",
        "country code",
        "country_code",
        "region",
        "locale",
        "land",
        "landcode",
        "regio",
      ],
    },

    {
      key: "invoice_date",
      label: "Invoice Date",
      required: false,
      synonyms: [
        "invoice date",
        "invoice_date",
        "date",
        "created",
        "created at",
        "created_at",
        "issued",
        "issued at",
        "issue date",
        "billing date",
        "factuurdatum",
        "aanmaakdatum",
        "boekingsdatum",
      ],
    },

    {
      key: "due_date",
      label: "Due Date",
      required: false,
      synonyms: [
        "due",
        "due date",
        "due_date",
        "payment due",
        "payment_due",
        "payment date",
        "expires",
        "expiry date",
        "deadline",
        "vervaldatum",
        "betaaldatum",
        "uiterste betaaldatum",
      ],
    },

    {
      key: "currency",
      label: "Currency",
      required: false,
      synonyms: [
        "currency",
        "currency code",
        "currency_code",
        "curr",
        "valuta",
        "valutacode",
        "munt",
        "munteenheid",
      ],
    },
  ],
};
