import type { DataProfile } from "../dataProfile";

export const invoiceFieldKeys = [
  "invoice_number",
  "company",
  "email",
  "amount",
  "vat",
  "status",
  "country",
  "invoice_date",
  "due_date",
  "currency",
] as const;

export type InvoiceField = (typeof invoiceFieldKeys)[number];

export type InvoiceFieldMapping = Record<InvoiceField, string>;

export const invoiceAllowedStatuses = [
  "ready",
  "paid",
  "draft",
  "pending",
  "sent",
] as const;

export const invoiceProfile: DataProfile<InvoiceField> = {
  id: "invoice",
  name: "Invoice Import",
  description:
    "Validate and prepare invoice data for safe import into business systems.",
  fields: [
    {
      key: "invoice_number",
      label: "Invoice Number",
      required: true,
      synonyms: [
        "invoice",
        "invoice number",
        "invoice no",
        "invoice no.",
        "invoice id",
        "invoice_id",
        "invoice nr",
        "invoice nr.",
        "invoice reference",
        "invoice ref",
        "invoice code",
        "invoice_code",
        "invoice_number",
        "invoiceid",
        "invoicenumber",
        "bill number",
        "bill no",
        "bill id",
        "voucher",
        "voucher number",
        "voucher no",
        "transaction reference",
        "transaction ref",
        "external reference",
        "external ref",
        "external id",
        "document",
        "document number",
        "document no",
        "document no.",
        "document id",
        "document_no",
        "doc no",
        "doc no.",
        "doc number",
        "doc id",
        "ref",
        "reference",
        "reference number",
        "reference no",
        "number",
        "no",
        "id",
        "factuur",
        "factuurnummer",
        "factuur nummer",
        "factuurnr",
        "factuur nr",
        "factuur nr.",
        "factuur referentie",
        "factuurreferentie",
        "boekstuk",
        "boekstuknummer",
        "boekstuk nr",
        "documentnummer",
        "document nummer",
        "referentie",
        "referentienummer",
        "nummer",
      ],
    },
    {
      key: "company",
      label: "Company",
      required: true,
      synonyms: [
        "company",
        "company name",
        "client",
        "client name",
        "customer",
        "customer name",
        "customer_name",
        "customername",
        "account",
        "account name",
        "account_name",
        "business",
        "business name",
        "organization",
        "organisation",
        "organization name",
        "organisation name",
        "vendor",
        "vendor name",
        "supplier",
        "supplier name",
        "buyer",
        "buyer name",
        "recipient",
        "recipient name",
        "billing name",
        "billing company",
        "invoice recipient",
        "invoice customer",
        "debtor",
        "debtor name",
        "debtor_name",
        "debtor number",
        "debtor no",
        "bedrijf",
        "bedrijfsnaam",
        "klant",
        "klantnaam",
        "klant naam",
        "relatie",
        "relatienaam",
        "debiteur",
        "debiteurnaam",
        "debiteur naam",
        "leverancier",
        "leveranciersnaam",
        "afnemer",
        "ontvanger",
        "factuuradres naam",
        "factuurklant",
      ],
    },
    {
      key: "email",
      label: "Email",
      required: true,
      synonyms: [
        "email",
        "e-mail",
        "mail",
        "email address",
        "email_address",
        "emailaddress",
        "customer email",
        "client email",
        "billing email",
        "billing_email",
        "invoice email",
        "invoice_email",
        "contact email",
        "contact mail",
        "contact_email",
        "finance email",
        "accounts email",
        "accounts payable email",
        "ap email",
        "debtor email",
        "debtor_email",
        "recipient email",
        "factuur email",
        "factuurmail",
        "factuur e-mail",
        "klant email",
        "klant e-mail",
        "debiteur email",
        "debiteur e-mail",
        "contact emailadres",
        "emailadres",
      ],
    },
    {
      key: "amount",
      label: "Amount",
      required: true,
      synonyms: [
        "amount",
        "invoice amount",
        "invoice_amount",
        "invoice total",
        "invoice_total",
        "total",
        "total amount",
        "total_amount",
        "grand total",
        "gross total",
        "gross_amount",
        "gross amount",
        "net amount",
        "net_amount",
        "subtotal",
        "sub total",
        "balance",
        "balance due",
        "open amount",
        "outstanding amount",
        "payment amount",
        "price",
        "value",
        "debit",
        "credit",
        "bedrag",
        "factuurbedrag",
        "factuur bedrag",
        "totaal",
        "totaalbedrag",
        "totaal bedrag",
        "brutobedrag",
        "bruto bedrag",
        "netto",
        "nettobedrag",
        "netto bedrag",
        "openstaand bedrag",
        "saldo",
        "waarde",
      ],
    },
    {
      key: "vat",
      label: "VAT",
      required: true,
      synonyms: [
        "vat",
        "vat amount",
        "vat_amount",
        "vat total",
        "vat_total",
        "tax",
        "tax amount",
        "tax_amount",
        "tax total",
        "tax_total",
        "sales tax",
        "sales_tax",
        "tax value",
        "taxvalue",
        "btw",
        "btw bedrag",
        "btwbedrag",
        "btw totaal",
        "btwtotaal",
        "belasting",
        "belastingbedrag",
        "belasting bedrag",
        "omzetbelasting",
        "omzetbelasting bedrag",
      ],
    },
    {
      key: "status",
      label: "Status",
      required: false,
      synonyms: [
        "status",
        "state",
        "payment status",
        "payment_status",
        "invoice status",
        "invoice_status",
        "workflow status",
        "workflow_status",
        "workflow",
        "stage",
        "phase",
        "processing status",
        "import status",
        "posting status",
        "posted",
        "paid status",
        "open status",
        "fase",
        "betaling status",
        "betaalstatus",
        "factuurstatus",
        "workflowstatus",
        "verwerkingsstatus",
        "boekingsstatus",
        "geboekt",
        "openstaand",
      ],
    },
    {
      key: "country",
      label: "Country",
      required: false,
      synonyms: [
        "country",
        "country code",
        "country_code",
        "countrycode",
        "region",
        "locale",
        "market",
        "territory",
        "billing country",
        "customer country",
        "client country",
        "debtor country",
        "land",
        "landcode",
        "land code",
        "regio",
        "markt",
        "factuurland",
        "klantland",
        "debiteurland",
      ],
    },
    {
      key: "invoice_date",
      label: "Invoice Date",
      required: false,
      synonyms: [
        "invoice date",
        "invoice_date",
        "invoicedate",
        "date",
        "document date",
        "document_date",
        "doc date",
        "created",
        "created at",
        "created_at",
        "issued",
        "issued at",
        "issue date",
        "issue_date",
        "billing date",
        "billing_date",
        "posting date",
        "posting_date",
        "book date",
        "book_date",
        "transaction date",
        "transaction_date",
        "factuurdatum",
        "factuur datum",
        "datum",
        "documentdatum",
        "boekingsdatum",
        "aanmaakdatum",
        "uitgiftedatum",
        "transactiedatum",
      ],
    },
    {
      key: "due_date",
      label: "Due Date",
      required: false,
      synonyms: [
        "due",
        "due date",
        "due_date",
        "duedate",
        "payment due",
        "payment_due",
        "payment date",
        "payment_date",
        "expires",
        "expiry date",
        "expiry_date",
        "deadline",
        "due on",
        "pay before",
        "payment deadline",
        "term date",
        "vervaldatum",
        "verval datum",
        "betaaldatum",
        "uiterste betaaldatum",
        "betaal voor",
        "betaling voor",
        "betalingstermijn",
        "deadline betaling",
      ],
    },
    {
      key: "currency",
      label: "Currency",
      required: false,
      synonyms: [
        "currency",
        "currency code",
        "currency_code",
        "currencycode",
        "curr",
        "ccy",
        "iso currency",
        "invoice currency",
        "billing currency",
        "payment currency",
        "valuta",
        "valutacode",
        "valuta code",
        "munt",
        "munteenheid",
        "factuurvaluta",
        "betaalvaluta",
      ],
    },
  ],
};
